# Metasearch config file.
#
# Anywhere in this file, you can reference environment variables using
# placeholders such as ${FOOBAR} that Metasearch will expand at runtime (if
# using Docker, remember to pass the host's env vars through to the container
# via `docker run` flags such as `-e ZOOM_KEY`).


###############################################################################
# ENGINE CONFIG
#
# An "engine" is an individual content source, e.g. Confluence. All supported
# engines are listed below.
#
# You should customize the config values (required unless stated otherwise) for
# all engines that you plan to use and simply delete the entries for any engines
# that you don't plan to use.
#
# Each engine's config accepts an optional `name` key (not shown in this
# example) that you may declare to override the engine's default name for
# display purposes, e.g. `name: Employee directory` in Pingboard's config.
###############################################################################
engines:

  # Nagios Core hosts and services (requires Nagios Core 4.x)
  nagios:
    # Nagios server hostname (and optional port)
    host: status.int.pgmac.net:8000
    # Protocol: http or https (optional, defaults to https)
    protocol: http
    # Nagios web UI username
    username: nagiosadmin
    # Nagios web UI password
    password: admin
    # Base path of Nagios web UI (optional, defaults to /nagios)
    # path: /nagios
    # Base path of PNP4Nagios for graph links (optional, omit to disable graph results)
    # graphsPath: /pnp4nagios

###############################################################################
# ADVANCED CONFIG
#
# All config properties below are optional and commented out by default.
###############################################################################

# Some custom HTML to render at the bottom of the page
# footer: 'Lorem ipsum dolor sit amet'

# Google Analytics tracking ID
# trackingId: UA-00000000-00
