name: Build a bill of materials ... and scan it

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions: read-all

jobs:
  sbom:
    uses: pgmac-net/pg-actions/.github/workflows/sbom.yml@main
    permissions:
      actions: read
      checks: read
      deployments: read
      issues: read
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      statuses: read
      attestations: write
      contents: write:
      security-events: write
      id-token: write
