name: Build a bill of materials ... and scan it

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  sbom:
    uses: pgmac-net/pg-actions/.github/workflows/sbom.yml@main
    with:
      DT_APIKEY: ${{ secrets.DT_APIKEY }}
      DT_PROTOCOL: ${{ secrets.DT_PROTOCOL }}
      DT_HOST: ${{ secrets.DT_HOST }}
    permissions:
      attestations: write
      contents: write
      security-events: write
      id-token: write
      actions: read
