name: Build a bill of materials ... and scan it

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  sbom:
    uses: pgmac-net/pg-actions/.github/workflows/sbom.yml@main
    permissions:
      attestations: write
      contents: write
      security-events: write
      id-token: write
