name: Build a bill of materials ... and scan it

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  sbom:
    uses: pgmac-net/pg-actions/.github/workflows/sbom.yml@935d4b8bec17fd49d449914e406a7232d793aadd # main
    secrets: inherit
    permissions:
      attestations: write
      contents: write
      security-events: write
      id-token: write
      actions: read
      pull-requests: write
